### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by bjthehun** [panda-planner-dev/pandaPIengine#1]
While compiling pandaPIengine, I encountered the following issues:
1. Compilation requires gengetopt, which i hadn't installed first. Perhaps gengetopt should be mentioned as required in the README.
2. When linking the executable, the following error occurred:
```
/usr/bin/ld: intDataStructures/libintDataStructures.a(CompressedSequenceSet.cpp.o): in function `printMemory()':
CompressedSequenceSet.cpp:(.text+0x840): multiple definition of `printMemory()'; CMakeFiles/pandaPIengine.dir/Util.cpp.o:Util.cpp:(.text+0x6e0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pandaPIengine.dir/build.make:219: pandaPIengine] Error 1
make[1]: *** [CMakeFiles/Makefile2:205: CMakeFiles/pandaPIengine.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
After removing the `printMemory` definitions in `CompressedSequenceSet.cpp`, and adding an `include` for `Util.h`, pandaPIengine would compile successfully. Maybe an error occurred in Commits fc85ef76435665f6ea10fb683d006bac3ce0f259 or f086acf32537d34642a4a91fd7890fe0aa9c9478?

If it helps, my build configuration/environment was:
* Ubuntu 20.04.2 LTS
* g++ 9.3.0
* GNU Make 4.2.1
* CMake 3.16.3
* Default Build arguments used

**Comment by galvusdamor** [comment]
Issue has been resolved via email.
