### ISSUE TITLE
pandaPIengine timeouts -- accurate?

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIengine#11]
It seems like the pandaPIengine is terminating early on MacOS.

I tried to give it an hour to work, but it quite after less than 8m:

```
$ time pandaPIengine -p --timelimit=3600 p-003-005-005-005.panda
Random seed: 42
Time limit: 3600 seconds
Reading input from p-003-005-005-005.panda.
Killed: 9

real	7m32.846s
user	4m40.270s
sys	1m29.335s
```

I'm not sure what's going on with this "Killed: 9" message.  I assume it's a time out, but I don't really know.  Is there anything else it could be? I'm looking through the code with search and I don't see where this killing is happening.

**Comment by rpgoldman** [comment]
I note that mach does different things with signals, so I suppose this could be a Mac-specific problem...

**Comment by galvusdamor** [comment]
The "Killed: 9" means that your operating system has aborted the program. I.e. it was not the planner that stopped. The code 9 usually means that your program got an out-of-memory error. In the Minecraft instance you were using this is also quite "normal" ;)
