### ISSUE TITLE
Missing code section

### ISSUE THREAD

**Issue by NicoCav** [panda-planner-dev/pandaPIengine#5]
It is said in this ICAPS paper "Making Translations to Classical Planning Competitive with Other HTN Planners" that the code for HTN2SAS is integrated into this code :
"The code is integrated into the pandaPI system and can be found at https://github.com/panda-planner-dev/pandaPIengine."

The issue is, i can't find it anywhere, where can it be found?

**Comment by galvusdamor** [comment]
Hi Nico,

Hm. The code is available in a separate repository: https://github.com/galvusdamor/pandaPIengineToSAS
We probably wrote this into the paper and then forgot about actually integrating the code into the main-line planner. Do you need this time-critically?

Gregor

**Comment by NicoCav** [comment]
Hi Gregor,

Thanks for the reply, the new repository you linked me doesn't seem to be
public. I need to check your results and the translated files, when would
you be able to publish the code?

Nicolas

Le jeu. 16 févr. 2023, 17:44, Gregor Behnke ***@***.***> a
écrit :

**Comment by galvusdamor** [comment]
Hi Nicolas,

The repo is now public. I have also spend the time to properly integrate the translation into the main-line engine. I.e. the version at [pandaPIengineToSAS](https://github.com/galvusdamor/pandaPIengineToSAS) is now the main-line version from this repo plus the translation.

I have not yet added full explicit instructions on how to use it, but the `--help` should provide sufficient explanations. I'll write something here.

1. The translations work better (i.e. are smaller and faster to solve) if the grounder is called with certain options
  - For total order planning run the planner with `-2i` (no 2-regularisation) or `-2it` (with 2-regularisation)
  - For partial order, use the options `-2ie`.
3. To access the translation based engine, you need to provide arguments of the following type

>  ./pandaPIengine -2 --downward=/PATH/TO/FASTDOWNWARD/builds/release/bin/downward --iterate problem.sas

This will call the default configuration and iterate over the progression bound until a solution has been found. The starting progression bound is the computed minimal one. The encoding will be selected based on the characteristics of the problem and will either be the total-order one, the push encoding, or the parallel-sequences encoding.

The engine has a few additional features to override its defaults

- `--pgb X` sets the initial progression bound to X
- `--transtype X` sets the used translation to X where the choices are `push`, `parallelseq`, `to`, `postrips`, `pocond`. **IMPORTANT**: by default pandaPIengine will override your choice if he knows better, i.e., knows that one encoding will be better then the one chosen by you - but there will be an output if he does so. To force him to use the specified encoding add `--forceTransType`.
  - `push` is the Push encoding from the paper
  - `parallelseq` is the PSeq encoding from the paper
  - `postrips` is the "old" HTN2SAS encoding from the paper
  - `to` is the total order encoding with method compression. Method compression cannot be be disabled.
- `--pgbsteps X` sets the step size of the increment in the progression bound
- `--onlyGenerate` forces the planner not to try to solve the generated problem. I.e. you get the output SAS+ file for the specified progression bound and nothing else. This will disable iteration
- `--iterate` if provided the planner will iterate over the progression bound until a solution is found. If you don't provide it (which you *should* in general) it will stop after the first progression bound
- `--sasfile X` sets the name of the generated SAS+ file to X. By default this is `output.sas`. If you want to run multiple engines in parallel (e.g. on a cluster) you *must* change this to avoid name clashes.
- `--downwardConf X` sets the search configuration of Fast Downward to X. The argument X is provided directly to Fast Downward. If you don't provide this, the engine will use a default configuration which is reasonable (Enforced hill climbing with FF followed by lazy-greedy search with FF).

I have not yet run a full suite of experiments with the new code integration. The base code of the encoding is the same as in the paper. I however cannot exclude the possibility of an integration issue. I'll write something here once I have completed the test. At that time I will also integrate the code into this repository.


You can however already use the engine as is.
For checking what the translation does, you can use both the output.sas and the output of the engine - it e.g. tells you how many actions/operators it has generated for a given progression bound.

If you encounter any problem or have any question, please don't hesitate to ask.

**Comment by NicoCav** [comment]
Hi Gregor,

Thank you for your answer again ! I will try the full process and let you
know if I find any bug doing a full run.

Have a nice day,
Nicolas

Le ven. 17 févr. 2023, 12:53, Gregor Behnke ***@***.***> a
écrit :

**Comment by ipc2023-htn** [comment]
Hi Nicolas,

Just in case you are interested: there is a competition for HTN planners this year: [HTN IPC 2023](https://ipc2023-htn.github.io/#). If you want to join (I assume you have a planner of your own?), just [send me](mailto:g.behnke@uva.nl) an email.

Cheers,
Gregor
