### ISSUE TITLE
How do we interpret the HDDL plan output 

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIengine#8]
I implemented the toll domain problem from the paper about plan repair as reformulation.  I parsed this, grounded it, and then generated a plan. The problem is that the HDDL plan I get is in terms of the SAS domain, and not the input domain, and does not seem parse-able according to the HDDL plan format [here](https://gki.informatik.uni-freiburg.de/ipc2020/format.pdf).

In particular, here is the decomposition section of the plan:
```
root 0
13 move[F,H] -> <<move-more-ta;move-more-ta_splitted_1[F,H];_splitting_method_move-more-ta_splitted_1;0;-1,-2,1>;move[H,H];move-none;1;0,2> 14 15
1 move[A,H] -> <<<<move-more;move[C,H];move-more-ta;1;0,-1,-2>;move-more-ta_splitted_1[C,H];_splitting_method_move-more-ta_splitted_1;1;0,-1,-2,2>;move[D,H];move-more-ta;2;0,1,-1,-2,3>;move-more-ta_splitted_1[D,H];_splitting_method_move-more-ta_splitted_1;2;0,1,-1,-2,3,4> 2 3 4 13 16 17
0 __top[] -> __top_method 1
```

I was left with a number of questions:
1. I didn't see anything that indicates that `<` is an acceptable HDDL symbol constituent, and there's certainly nothing like that in the format document.  They also look like they are delimiters, but they are not balanced.
2. It's not terribly important, but there wasn't anything in that format document to indicate that the `NAME [ARG1,ARG2,..,ARGN]` format was acceptable for complex tasks: it's mentioned only specifically in connection with actions: "Alternatively, you can provide the *action’s* name and parameters in one of the following formats..." [emphasis mine]
3. The method names look like they were generated as a side-effect of the grounding process.  How are they to be translated back into the original method names from the domain?  I was expecting something more like this example from the format document:
   ```
   15 deliver package-1 city-loc-2 -> m-deliver 16 13 17 11
   ```
   I note that the actions although also presumably grounded have not lost their original names, For example, we see `drive-ta[C,D]` not a grounded version such as `drive-ta_c_d`.
4. A final question: if there are parameters that do not appear in the arguments to the complex task, I'm not sure how we find their values in the HDDL plan, if the preconditions are consistent with multiple alternative bindings.  Perhaps this is not an issue -- I have not thought it through carefully.

**Comment by galvusdamor** [comment]
Hi Robert,

This is a perfect example of "insider knowledge" and automatisms that we have, but that are not well documented.

1.  Indeed, `<` is not a valid character in an HDDL name. I've just had a look at your excerpt and they seem to be balanced.
2. `[` and `]` are also not allowed and the format `NAME [ARG1,ARG2,..,ARGN] ` is not an acceptable format for abstract tasks. The quote that you provide from the document is perfectly true!
3. Indeed! This is the "secret knowledge". The grounder heavily changes and re-writes he model s.t. it is better to plan for. In that process he e.g. combines multiple methods into one, splits methods up into several parts or adds or removes tasks or actions from the model. The strange names (including the `<`s) is the grounders way of keeping track of all of that. For example
```
<<<<move-more;move[C,H];move-more-ta;1;0,-1,-2>;move-more-ta_splitted_1[C,H];_splitting_method_move-more-ta_splitted_1;1;0,-1,-2,2>;move[D,H];move-more-ta;2;0,1,-1,-2,3>;move-more-ta_splitted_1[D,H];_splitting_method_move-more-ta_splitted_1;2;0,1,-1,-2,3,4>
```
in your plan is "just" four methods combined into one.

This was never intended as a valid plan output w.r.t. to the original HDDL - the plan that the pandaPIengine finds is only valid w.r.t. the grounded model.

To obtain a valid HDDL plan again you need to translate the plan back into its original format. For that, we have a feature in the pandaPIparser. Basically, you have to write the raw plan produced by the pandaPIengine into a file (e.g. `plan.original`) and then run
```
./pandaPIparser -c plan.original plan.actual
```
This will produce an HDDL conformant plan in the `plan.actual` file. This step will also take care of the `[` braces, which are also a side-effect of grounding. I have added documentation for this to the README.
4. Indeed, the HDDL plan format does not require you (and has no way of doing so, yet) these parameters. The verifier has a method `evaluateFormulaOnStateWithMissingAssignments` for this, which essentially searches over all possible compatible assignments and accepts the method if there is one assignment of the non-mentioned variables that fits. Note that this is only a problem for variables that only occur in the method preconditions. If they occur in either the decomposed task or in one of the subtasks, we still have this information.
5. Also in our internal raw plan format, this information is still present, as we compile method preconditions into actions whose name starts with `__method_preconditions` (or something similar). Their parameters are all the variables that are mentioned in that particular method precondition.

I deeply appreciate your feedback! I know that it must be a bit frustrating to work through pandaPI and to be held up by so may small problems. Your feedback allows us to see / know of the issues that we have not thought of so far and will surely improve the usability of the planner!

Cheers,
Gregor

**Comment by rpgoldman** [comment]
With your updates to the README.md, I think the answer is now easy enough to find, so I am closing this issue.
